"use context";

import { Inter } from "next/font/google";
import "./globals.css";
import { CategoryContextProvider } from "@/components/context/ChooseTheCategorycontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CategoryContextProvider>
        <body className={inter.className}>{children}</body>
      </CategoryContextProvider>
    </html>
  );
}
